services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - app-network
        depends_on:
            - mysql
        command: >
            sh -c "
            chmod +x scripts/install.sh &&
            ./scripts/install.sh &&
            php artisan serve --host=0.0.0.0 --port=80"
    
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'laravel'
        volumes:
            - 'mysql-data:/var/lib/mysql'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
