services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - app-network
        depends_on:
            - mysql
        command: >
            sh -c "
            composer install &&
            cp .env.example .env &&
            php artisan key:generate --force &&
            chmod +x scripts/install.sh &&
            ./scripts/install.sh &&
            php artisan serve --host=0.0.0.0 --port=80"
    
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'laravel'
            MYSQL_TESTING_DATABASE: 'testing'
        volumes:
            - 'mysql-data:/var/lib/mysql'
            - './docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
